[package]
name = "selffuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperhook = { path = "../../", features = ["kafl", "pt"]}
log = "0.4.19"
simplelog = { version = "0.12.1", features = ["termcolor"] }
libc = "*"
lazy_static = "1.4.0"

[build-dependencies]
cc = "1.0"